version: '3.4'

services:
  catalogdb:
    image: mongo 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
  
  basketdb:
    image: redis:alpine
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest  
 
  pgadmin:
    image: dpage/pgadmin4

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile  

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotApiGw/Dockerfile   

 
      


volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
