version: '3.4'

services:
  catalogdb:
    image: mongo
 

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
  
  basketdb:
    image: redis:alpine
  
  rabbitmq:
    image: rabbitmq:3-management-alpine


  portainer:
    image: portainer/portainer-ce

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile
    

volumes:
  mongo_data:
  portainer_data:
